// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nichehiking_cpp
List nichehiking_cpp(int grid, double torch_init, int cycles, int agemax, int changePeriod, double mortRate, int pneigh, int sneigh, int bneigh, double mu, double r);
RcppExport SEXP _symsympho_nichehiking_cpp(SEXP gridSEXP, SEXP torch_initSEXP, SEXP cyclesSEXP, SEXP agemaxSEXP, SEXP changePeriodSEXP, SEXP mortRateSEXP, SEXP pneighSEXP, SEXP sneighSEXP, SEXP bneighSEXP, SEXP muSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< double >::type torch_init(torch_initSEXP);
    Rcpp::traits::input_parameter< int >::type cycles(cyclesSEXP);
    Rcpp::traits::input_parameter< int >::type agemax(agemaxSEXP);
    Rcpp::traits::input_parameter< int >::type changePeriod(changePeriodSEXP);
    Rcpp::traits::input_parameter< double >::type mortRate(mortRateSEXP);
    Rcpp::traits::input_parameter< int >::type pneigh(pneighSEXP);
    Rcpp::traits::input_parameter< int >::type sneigh(sneighSEXP);
    Rcpp::traits::input_parameter< int >::type bneigh(bneighSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(nichehiking_cpp(grid, torch_init, cycles, agemax, changePeriod, mortRate, pneigh, sneigh, bneigh, mu, r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_symsympho_nichehiking_cpp", (DL_FUNC) &_symsympho_nichehiking_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_symsympho(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
