# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nichehiking_cpp <- function(grid = 100L, torch_init = 0.005, cycles = 1L, agemax = 1000L, changePeriod = 8L, mortRate = 0.1, pneigh = 3L, sneigh = 3L, bneigh = 3L, mu = 0.00001, r = 0.08, verbose) {
    .Call(`_symsympho_nichehiking_cpp`, grid, torch_init, cycles, agemax, changePeriod, mortRate, pneigh, sneigh, bneigh, mu, r, verbose)
}

